ClusterName=soperator
#
SlurmctldHost=controller-0(controller-0.soperator-controller-svc.soperator.svc.cluster.local)
SlurmctldHost=controller-1(controller-1.soperator-controller-svc.soperator.svc.cluster.local)
#
AuthType=auth/munge
CredType=cred/munge
#
#SlurmConfig Spec
DefMemPerNode=191488
DefCpuPerGPU=16
CompleteWait=5
DebugFlags=Cgroup,CPU_Bind,Gres,JobComp,Priority,Script,SelectType,Steps,TraceJobs
Epilog=/etc/slurm-scripts/epilog.sh
Prolog=/etc/slurm-scripts/prolog.sh
MaxJobCount=10000
MinJobAge=86400
MessageTimeout=30
#
GresTypes=gpu
MpiDefault=pmix
MailProg=/usr/bin/true
PluginDir=/usr/lib/x86_64-linux-gnu/slurm
ProctrackType=proctrack/cgroup
ReturnToService=2
#
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmctldPort=6817
#
SlurmdPidFile=/var/run/slurmd.pid
SlurmdPort=6818
#
SlurmdSpoolDir=/var/spool/slurmd
#
SlurmUser=root
#
StateSaveLocation=/var/spool/slurmctld
#
TaskPlugin=task/cgroup,task/affinity
#
CliFilterPlugins=cli_filter/user_defaults
#
LaunchParameters=use_interactive_step
#Scrontab
ScronParameters=enable,explicit_scancel
#
PropagateResourceLimits=NONE
#
#HEALTH CHECKS
#https://slurm.schedmd.com/slurm.conf.html#OPT_HealthCheckInterval
HealthCheckInterval=30
HealthCheckProgram=/usr/bin/gpu_healthcheck.sh
HealthCheckNodeState=ANY
#
InactiveLimit=0
KillOnBadExit=1
KillWait=180
UnkillableStepTimeout=600
SlurmctldTimeout=30
SlurmdTimeout=180
WaitTime=0
#
#SCHEDULING
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory,CR_CORE_DEFAULT_DIST_BLOCK
#
#LOGGING
SlurmctldDebug=info
SlurmctldLogFile=/dev/null
SlurmdDebug=info
SlurmdLogFile=/dev/null
#
#COMPUTE NODES
#We're using the "dynamic nodes" feature: https://slurm.schedmd.com/dynamic_nodes.html
MaxNodeCount=1024
MaxArraySize=1024
JobRequeue=1
PreemptMode=REQUEUE
PreemptType=preempt/partition_prio
#Partition Configuration
PartitionName=main Nodes=ALL Default=YES MaxTime=INFINITE State=UP OverSubscribe=YES
#
#ACCOUNTING
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=soperator-accounting-svc.soperator.svc.cluster.local
AccountingStorageUser=accounting
AccountingStoragePort=6819
JobCompType=jobcomp/none
AccountingStorageTRES=CPU,Mem,Node,VMem,Gres/gpu
JobAcctGatherType=jobacct_gather/cgroup
PriorityWeightAge=0
PriorityWeightFairshare=0
PriorityWeightQOS=0
#
#REST API
AuthAltTypes=auth/jwt
AuthAltParameters=jwt_key=/var/spool/slurmctld/jwt_hs256.key
#
#Include custom_slurm.conf
include custom_slurm.conf